language: cpp

env:
  global:
   - secure: "lACMH9UalN+PPhuX8NN/qEbLldL63U84WkRiHkjTEaReYV1Fm/ksiVQJnYygE1+aaxSlOi75WoveBrAcJcRui2rUGccqy69/YtKXA5oxT90aUfosEEUHChoOdJvYlA/mKQirHYymrZgCt7TNkhq425YGs9fTmxZsipKCfdejFIfy86wVVMkZJ64bfDnqZQfF55ks5HkpRTRYdCVkwHrZoZVH6gbhbDlvqEQZLjIHq9H72A9wcI24Xjz7sjdJ6uMy1Ce3UOLvIWqisK5jkcq7U4yotj5iuhdW9rEjIsWIr6AZKrXZPmKrYwdlRBesG+UU2+2iB0ltE74iqMeU5Td9sSYrASLyKA6XmbiA95dikLMrYLTqvO58mLKUG87AN2bbEgqZXDauWTlxJzDbvecwEBJl8ecDtt5L2zcKjq7MYNb6+HQMFBSiWHEXF8rvk1s8E7B0MBbOzo6Fsn+fT+iUdp6nG33SBAwZoIbcpMYful48x7o0pfTkzOxZtMywW7e4dq+6Vmt1e37yDGi4895bPPEL9W7bfHGKwaRetxZ71Q2Xckj5wPZ1fYvln6+V5IzQLSNYOLLrXXGSCcOeaqA/FzUZhKlvpoSKUhZyuIAnpgaVcpcP13qOvlXg/YYtxe9wcXd8lGDp736B3fr/FaZhYKHmHTJV8pBRLV9X3KMblfA="

matrix:
  include:
  - os: osx
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: tFQgVI1RocYrMW4aaPrg3Pamsmbyb0XWb4YPUUYP/uTTVA3mM05bEHXpzUgo5Lg2UDsIrW6+eAJFLkx2IeB9Lw7RFoeRPBkAHVKzUDr5uXr7Fl98UlYHBV+vhCBQg3L/zmWnYGiEDROQ2SVtsA9wifZVFOFo4dIMP73G8ueSoKKS35s1GIIOs98c+T0S2fDIycoKgPRTUtI4XO/EuMON82ysxppmoN7XoO5lcgLfpHd7+3XQDwlwloGMNWbhARi4tLWrU1ANySPFs9aOzmb7DDKjMPgScdwcMY0X3si5I/IZ9NT8zBgHa6hwtcrob82p0Z3qomkmfJpju0hs6kXwOWRUJCR6BxMzx7L5QKBgzZ5fwoTaptkMjBeeaq9E7jEWP9kMdqJ39CU9YBLRo6l70OJVYT6KbSDbUJZhFzi7LP04hl+G6uXVUVRPxkNNef3lJ7kEzx/d0U+6TR6Lgw6R6iPLczOvvcu2ks8w606o2fxOcCW5wFMm6YJif2qRE3274amT88rb/CO+L0ePq8rVZmCrJnGXzsPWW0JGxXMYleP8KDd54296u3G2aEjvaq2a4G1aLiMkGsHGshmLmv9aVAavpVX3cIuxRepq58Bgul3tWLKb+UJ98q8IAjn5m9qgdBYmJBDL5Ep5XXQ6QwKEvaCWTG2k11pP8xD8SqilcNQ=
      on:
        tags: true
  - os: osx
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme AppleALC -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme AppleALC -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

  - os: osx
    compiler: clang

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/AppleALC"
          description: "AppleALC"
        notification_email: $NOTIFICATION_EMAIL
        build_command_prepend: "src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval \"$src\" || exit 1 ; src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/covstrap.sh) && eval \"$src\" || exit 1"
        build_command: "xcodebuild -configuration Release"
        branch_pattern: master
